/*
 * kernelctl — unified kernel and boot configuration management across Linux bootloaders.
 * Copyright (C) 2026 Luka Gejak
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License, version 3, as published
 * by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * Alternatively, this file is available under a commercial licence that lifts
 * the obligations of the GPL. Enquiries: lukagejak5@gmail.com
 */
//! GRUB 2.
//!
//! GRUB spreads its state over three files and each one answers a different
//! question:
//!
//! - `grub.cfg` is the generated menu. It is the only place the entries
//!   themselves exist, but it is regenerated by `grub-mkconfig` on every
//!   kernel upgrade, so edits to it are temporary by nature.
//! - `grubenv` is the writable environment block holding `saved_entry` (the
//!   default) and `next_entry` (the one-shot). This is what `grub-set-default`
//!   and `grub-reboot` touch, and it survives regeneration.
//! - `/etc/default/grub` is the template input. Changes here are permanent but
//!   only take effect after `grub-mkconfig` runs.
//!
//! So the default and one-shot are written to `grubenv` - permanent and
//! immediate - while timeout and command-line changes are written to both
//! `grub.cfg` (immediate) and `/etc/default/grub` (survives regeneration),
//! with a note telling the user which is which.

use std::path::PathBuf;

use crate::error::{Error, Result};
use crate::model::{BootEntry, EntryFlags, LoaderKind};
use crate::sys::atomic::{self, WriteOutcome};

use super::{
    grubenv::{self, GrubEnv},
    resolve_under,
    scan::BootRoots,
    Bootloader, Capabilities, Context, Timeout,
};

/// Variable holding the persistent default.
const VAR_SAVED: &str = "saved_entry";
/// Variable holding the one-shot default, cleared by GRUB after it boots.
const VAR_NEXT: &str = "next_entry";

pub struct Grub2 {
    cfg: PathBuf,
    /// Resolved at detection time from the scan's config directories, so a
    /// scoped scan does not read the running system's /etc/default/grub.
    default_grub: Option<PathBuf>,
    env: PathBuf,
    /// Partition the paths inside grub.cfg are relative to.
    boot_root: PathBuf,
    confidence: u8,
}

// ---------------------------------------------------------------------------
// grub.cfg parsing
// ---------------------------------------------------------------------------

/// A menu entry as it appears in grub.cfg.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct MenuEntry {
    pub title: String,
    /// Value of `$menuentry_id_option`, which is what `saved_entry` stores.
    pub id: Option<String>,
    pub kernel: Option<String>,
    pub cmdline: String,
    pub initrds: Vec<String>,
    pub devicetree: Option<String>,
    /// GRUB's positional address, e.g. `0` or `1>2` inside a submenu.
    pub index_path: String,
    pub depth: u8,
    pub is_submenu: bool,
    /// Line index of the `linux` line, so a cmdline edit can target it.
    pub linux_line: Option<usize>,
}

/// Split a grub.cfg line into shell-style tokens, honouring quotes.
///
/// GRUB's config language is shell-like: titles are quoted and may contain
/// spaces and braces, so a naive whitespace split mis-parses them and a naive
/// brace count loses track of nesting.
fn tokenize(line: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut cur = String::new();
    let mut quote: Option<char> = None;
    let mut escaped = false;
    let mut has = false;

    for ch in line.chars() {
        if escaped {
            cur.push(ch);
            escaped = false;
            has = true;
            continue;
        }
        match ch {
            '\\' if quote != Some('\'') => escaped = true,
            '\'' | '"' if quote.is_none() => {
                quote = Some(ch);
                has = true;
            }
            c if Some(c) == quote => {
                quote = None;
                has = true;
            }
            c if c.is_whitespace() && quote.is_none() => {
                if has {
                    out.push(std::mem::take(&mut cur));
                    has = false;
                }
            }
            c => {
                cur.push(c);
                has = true;
            }
        }
    }
    if has {
        out.push(cur);
    }
    out
}

/// Net brace depth change on a line, ignoring braces inside quotes.
fn brace_delta(line: &str) -> i32 {
    let mut depth = 0;
    let mut quote: Option<char> = None;
    let mut escaped = false;

    for ch in line.chars() {
        if escaped {
            escaped = false;
            continue;
        }
        match ch {
            '\\' if quote != Some('\'') => escaped = true,
            '\'' | '"' if quote.is_none() => quote = Some(ch),
            c if Some(c) == quote => quote = None,
            '{' if quote.is_none() => depth += 1,
            '}' if quote.is_none() => depth -= 1,
            // A comment runs to end of line, so stop counting.
            '#' if quote.is_none() => break,
            _ => {}
        }
    }
    depth
}

/// Extract the menuentry id from a `menuentry`/`submenu` line.
///
/// Generated configs write `$menuentry_id_option 'gnulinux-...'`; hand-written
/// ones use `--id foo`. Both forms put the id in the token after the marker.
fn extract_id(tokens: &[String]) -> Option<String> {
    tokens
        .iter()
        .position(|t| t == "$menuentry_id_option" || t == "--id")
        .and_then(|i| tokens.get(i + 1))
        .cloned()
}

/// Parse every entry out of a grub.cfg.
pub fn parse_cfg(text: &str) -> Vec<MenuEntry> {
    let lines: Vec<&str> = text.lines().collect();
    let mut out: Vec<MenuEntry> = Vec::new();

    // One counter per nesting level, giving GRUB's `1>2` addressing.
    let mut counters: Vec<usize> = vec![0];
    // Brace depth at which each open submenu started, so we know when it ends.
    let mut submenu_depths: Vec<i32> = Vec::new();
    let mut depth: i32 = 0;

    let mut i = 0;
    while i < lines.len() {
        let line = lines[i];
        let trimmed = line.trim_start();
        let tokens = tokenize(trimmed);
        let keyword = tokens.first().map(String::as_str).unwrap_or("");

        if keyword == "menuentry" || keyword == "submenu" {
            let is_submenu = keyword == "submenu";
            // The first token after the keyword that is not a flag is the
            // title. Generated configs put it immediately after.
            let title = tokens.get(1).cloned().unwrap_or_default();
            let level = counters.len() - 1;

            let mut index_path = String::new();
            for (n, c) in counters.iter().enumerate() {
                if n > 0 {
                    index_path.push('>');
                }
                index_path.push_str(&c.to_string());
            }

            let mut entry = MenuEntry {
                title,
                id: extract_id(&tokens),
                index_path,
                depth: level as u8,
                is_submenu,
                ..Default::default()
            };

            depth += brace_delta(line);

            if is_submenu {
                // Descend: children are numbered from zero within the submenu.
                // The parent's counter is deliberately *not* advanced yet -
                // children address as `parent>child` using the parent's own
                // index, so it must keep that value until the submenu closes.
                submenu_depths.push(depth);
                counters.push(0);
                out.push(entry);
                i += 1;
                continue;
            }
            *counters.last_mut().unwrap() += 1;

            // A menuentry body runs until the brace depth returns to where it
            // was before the opening brace.
            let body_start_depth = depth;
            let mut j = i + 1;
            while j < lines.len() && depth >= body_start_depth {
                let body_line = lines[j];
                parse_body_line(&mut entry, body_line, j);
                depth += brace_delta(body_line);
                if depth < body_start_depth {
                    break;
                }
                j += 1;
            }
            out.push(entry);
            i = j + 1;

            // Leaving a menuentry can also close the submenu containing it.
            close_submenus(depth, &mut submenu_depths, &mut counters);
            continue;
        }

        depth += brace_delta(line);
        // A closing brace may end a submenu.
        close_submenus(depth, &mut submenu_depths, &mut counters);
        i += 1;
    }

    out
}

/// Pop any submenus whose closing brace we have now passed.
///
/// The parent's counter is advanced here rather than when the submenu opened:
/// while we are inside it, children address themselves as `parent>child` and
/// need the parent's own index to still be current.
fn close_submenus(depth: i32, submenu_depths: &mut Vec<i32>, counters: &mut Vec<usize>) {
    while submenu_depths.last().is_some_and(|d| depth < *d) {
        submenu_depths.pop();
        if counters.len() > 1 {
            counters.pop();
            *counters.last_mut().expect("a parent level always remains") += 1;
        }
    }
}

/// Pull kernel, initrd and devicetree out of one line of a menuentry body.
fn parse_body_line(entry: &mut MenuEntry, line: &str, line_no: usize) {
    let tokens = tokenize(line.trim_start());
    let Some(keyword) = tokens.first() else { return };

    match keyword.as_str() {
        // linux16 and linuxefi are the BIOS and EFI variants; all three take
        // the kernel path first and the command line after it.
        "linux" | "linux16" | "linuxefi" => {
            if let Some(path) = tokens.get(1) {
                entry.kernel = Some(path.clone());
                entry.cmdline = tokens[2..].join(" ");
                entry.linux_line = Some(line_no);
            }
        }
        "initrd" | "initrd16" | "initrdefi" => {
            // A single initrd line may list several images.
            entry.initrds.extend(tokens[1..].iter().cloned());
        }
        "devicetree" => entry.devicetree = tokens.get(1).cloned(),
        _ => {}
    }
}

// ---------------------------------------------------------------------------
// /etc/default/grub
// ---------------------------------------------------------------------------

/// Read a `KEY=value` setting from /etc/default/grub, unquoting the value.
pub fn default_grub_get(text: &str, key: &str) -> Option<String> {
    for line in text.lines() {
        let line = line.trim();
        if line.starts_with('#') {
            continue;
        }
        let Some((k, v)) = line.split_once('=') else { continue };
        if k.trim() != key {
            continue;
        }
        return Some(unquote(v.trim()));
    }
    None
}

/// Set a `KEY=value` setting, preserving comments and the rest of the file.
pub fn default_grub_set(text: &str, key: &str, value: &str) -> String {
    // Always quote: these values routinely contain spaces, and an unquoted
    // GRUB_CMDLINE_LINUX would be read by the shell as several assignments.
    let assignment = format!("{key}=\"{}\"", value.replace('"', "\\\""));
    let mut out = Vec::new();
    let mut replaced = false;

    for line in text.lines() {
        let is_key = !line.trim_start().starts_with('#')
            && line.split_once('=').is_some_and(|(k, _)| k.trim() == key);
        if is_key && !replaced {
            out.push(assignment.clone());
            replaced = true;
        } else if !is_key {
            out.push(line.to_string());
        }
    }
    if !replaced {
        out.push(assignment);
    }
    let mut joined = out.join("\n");
    joined.push('\n');
    joined
}

fn unquote(v: &str) -> String {
    let v = v.trim();
    if v.len() >= 2 {
        let b = v.as_bytes();
        if (b[0] == b'"' || b[0] == b'\'') && b[b.len() - 1] == b[0] {
            return v[1..v.len() - 1].to_string();
        }
    }
    // Strip a trailing comment from an unquoted value.
    v.split_once(" #").map(|(a, _)| a.trim().to_string()).unwrap_or_else(|| v.to_string())
}

// ---------------------------------------------------------------------------
// Adapter
// ---------------------------------------------------------------------------

impl Grub2 {
    pub fn detect(roots: &BootRoots) -> Option<Grub2> {
        for root in &roots.boot {
            // Debian and Arch use grub/, Fedora and SUSE use grub2/.
            for name in ["grub", "grub2"] {
                let dir = root.join(name);
                let cfg = dir.join("grub.cfg");
                let _ = &dir;
                if !cfg.is_file() {
                    continue;
                }
                let env = dir.join("grubenv");
                // A writable environment block means set-default and set-next
                // work without regenerating the menu, so it is worth more than
                // a lone config file.
                let confidence = if env.exists() { 92 } else { 80 };
                return Some(Grub2 {
                    cfg,
                    default_grub: roots.find_config("default/grub"),
                    env,
                    boot_root: root.clone(),
                    confidence,
                });
            }
        }
        None
    }

    fn load_env(&self) -> GrubEnv {
        GrubEnv::load(&self.env).unwrap_or_else(|_| GrubEnv::empty())
    }

    /// Does grub.cfg actually consult `saved_entry`?
    ///
    /// It only does so when the config was generated with `GRUB_DEFAULT=saved`.
    /// Without that, writing the environment block has no effect and the user
    /// needs to be told.
    fn honours_saved_entry(&self) -> bool {
        std::fs::read_to_string(&self.cfg)
            .map(|t| t.contains("saved_entry"))
            .unwrap_or(false)
    }

    fn default_grub_path(&self) -> Option<PathBuf> {
        self.default_grub.clone()
    }

    /// Resolve which parsed entry the given `saved_entry`/`next_entry` value
    /// refers to. GRUB accepts an id, a title or a positional index.
    fn value_matches(value: &str, entry: &MenuEntry) -> bool {
        let value = value.trim();
        if value.is_empty() {
            return false;
        }
        entry.id.as_deref() == Some(value)
            || entry.title == value
            || entry.index_path == value
    }
}

fn timeout_to_grub(t: Timeout) -> String {
    match t {
        Timeout::Immediate => "0".into(),
        Timeout::Seconds(n) => n.to_string(),
        // GRUB spells "wait forever" as -1.
        Timeout::Indefinite => "-1".into(),
    }
}

fn timeout_from_grub(v: &str) -> Option<Timeout> {
    let v = v.trim();
    if v == "-1" {
        return Some(Timeout::Indefinite);
    }
    match v.parse::<u32>() {
        Ok(0) => Some(Timeout::Immediate),
        Ok(n) => Some(Timeout::Seconds(n)),
        Err(_) => None,
    }
}

/// Replace the command line on a specific `linux` line of grub.cfg.
fn rewrite_linux_line(text: &str, line_no: usize, cmdline: &str) -> Result<String> {
    let mut lines: Vec<String> = text.lines().map(str::to_string).collect();
    let line = lines
        .get(line_no)
        .ok_or_else(|| Error::other("grub.cfg changed on disk since it was read"))?;

    let indent: String = line.chars().take_while(|c| c.is_whitespace()).collect();
    let tokens = tokenize(line.trim_start());
    let keyword = tokens.first().cloned().unwrap_or_else(|| "linux".into());
    let kernel = tokens.get(1).cloned().unwrap_or_default();

    lines[line_no] = format!("{indent}{keyword} {kernel} {cmdline}").trim_end().to_string();

    let mut joined = lines.join("\n");
    joined.push('\n');
    Ok(joined)
}

impl Bootloader for Grub2 {
    fn kind(&self) -> LoaderKind {
        LoaderKind::Grub2
    }

    fn capabilities(&self) -> Capabilities {
        Capabilities::SET_DEFAULT
            | Capabilities::SET_ONESHOT
            | Capabilities::TIMEOUT
            | Capabilities::EDIT_CMDLINE
            | Capabilities::GENERATED
    }

    fn confidence(&self) -> u8 {
        self.confidence
    }

    fn config_files(&self) -> Vec<PathBuf> {
        [Some(self.cfg.clone()), Some(self.env.clone()), self.default_grub.clone()]
            .into_iter()
            .flatten()
            .filter(|p| p.exists())
            .collect()
    }

    fn post_write_note(&self) -> Option<String> {
        Some(format!(
            "{} is generated by grub-mkconfig and will be rewritten on the next \
             kernel upgrade; settings mirrored into /etc/default/grub survive that",
            self.cfg.display()
        ))
    }

    fn entries(&self, _ctx: &Context) -> Result<Vec<BootEntry>> {
        let text = atomic::read_to_string(&self.cfg)?;
        let parsed = parse_cfg(&text);
        let env = self.load_env();
        let saved = env.get(VAR_SAVED).unwrap_or_default().to_string();
        let next = env.get(VAR_NEXT).unwrap_or_default().to_string();

        let mut out = Vec::new();
        for menu in &parsed {
            // saved_entry stores the id when there is one, so prefer it and
            // fall back to the positional address.
            let native_id = menu.id.clone().unwrap_or_else(|| menu.index_path.clone());
            let mut entry =
                BootEntry::new(LoaderKind::Grub2, &self.cfg, &native_id, &menu.title);

            entry.kernel = menu.kernel.as_deref().map(|p| resolve_under(&self.boot_root, p));
            entry.initrds =
                menu.initrds.iter().map(|p| resolve_under(&self.boot_root, p)).collect();
            entry.devicetree =
                menu.devicetree.as_deref().map(|p| resolve_under(&self.boot_root, p));
            entry.cmdline = menu.cmdline.clone();
            entry.depth = menu.depth;

            if menu.is_submenu {
                entry.flags.insert(EntryFlags::SUBMENU);
            }
            if !saved.is_empty() && Grub2::value_matches(&saved, menu) {
                entry.flags.insert(EntryFlags::DEFAULT);
            }
            if !next.is_empty() && Grub2::value_matches(&next, menu) {
                entry.flags.insert(EntryFlags::ONESHOT);
            }

            entry.extra.insert("index".into(), menu.index_path.clone());
            if let Some(line) = menu.linux_line {
                entry.extra.insert("cfg-line".into(), (line + 1).to_string());
            }

            out.push(entry);
        }

        // Nothing in grubenv: fall back to the static `set default=` the
        // generated config carries.
        if saved.is_empty() {
            if let Some(value) = text
                .lines()
                .find_map(|l| l.trim().strip_prefix("set default="))
                .map(|v| unquote(v.trim()))
            {
                if !value.contains("saved_entry") {
                    if let Some(e) = out
                        .iter_mut()
                        .zip(parsed.iter())
                        .find(|(_, m)| Grub2::value_matches(&value, m))
                        .map(|(e, _)| e)
                    {
                        e.flags.insert(EntryFlags::DEFAULT);
                    }
                }
            }
        }

        Ok(out)
    }

    fn set_default(&self, ctx: &Context, entry: &BootEntry) -> Result<Vec<WriteOutcome>> {
        ctx.preflight_write("set-default", &self.env)?;
        if ctx.dry_run {
            return Ok(Vec::new());
        }

        let mut env = self.load_env();
        env.set(VAR_SAVED, &entry.native_id)?;
        grubenv::write_in_place(&self.env, &env)?;

        let mut outcomes = vec![WriteOutcome {
            target: self.env.clone(),
            backup: Some(atomic::backup_path_for(&self.env)),
        }];

        // Writing saved_entry only has an effect if the generated menu reads
        // it, which requires GRUB_DEFAULT=saved. Set that too, so the choice
        // survives the next grub-mkconfig run.
        if !self.honours_saved_entry() {
            if let Some(path) = self.default_grub_path() {
                let text = atomic::read_to_string(&path)?;
                if default_grub_get(&text, "GRUB_DEFAULT").as_deref() != Some("saved") {
                    let updated = default_grub_set(&text, "GRUB_DEFAULT", "saved");
                    outcomes.push(atomic::write_atomic(&path, updated.as_bytes())?);
                }
            }
        }

        Ok(outcomes)
    }

    fn set_oneshot(&self, ctx: &Context, entry: &BootEntry) -> Result<Vec<WriteOutcome>> {
        ctx.preflight_write("set-next", &self.env)?;
        if ctx.dry_run {
            return Ok(Vec::new());
        }
        let mut env = self.load_env();
        env.set(VAR_NEXT, &entry.native_id)?;
        grubenv::write_in_place(&self.env, &env)?;
        Ok(vec![WriteOutcome {
            target: self.env.clone(),
            backup: Some(atomic::backup_path_for(&self.env)),
        }])
    }

    fn clear_oneshot(&self, ctx: &Context) -> Result<Vec<WriteOutcome>> {
        ctx.preflight_write("set-next --clear", &self.env)?;
        if ctx.dry_run {
            return Ok(Vec::new());
        }
        let mut env = self.load_env();
        env.remove(VAR_NEXT);
        grubenv::write_in_place(&self.env, &env)?;
        Ok(vec![WriteOutcome {
            target: self.env.clone(),
            backup: Some(atomic::backup_path_for(&self.env)),
        }])
    }

    fn timeout(&self, _ctx: &Context) -> Result<Option<Timeout>> {
        // /etc/default/grub is the source of truth; grub.cfg only reflects the
        // last time it was generated.
        if let Some(path) = self.default_grub_path() {
            if let Ok(text) = std::fs::read_to_string(&path) {
                if let Some(t) = default_grub_get(&text, "GRUB_TIMEOUT").as_deref().and_then(timeout_from_grub) {
                    return Ok(Some(t));
                }
            }
        }
        let Ok(cfg) = std::fs::read_to_string(&self.cfg) else { return Ok(None) };
        Ok(cfg
            .lines()
            .find_map(|l| l.trim().strip_prefix("set timeout="))
            .map(|v| unquote(v.trim()))
            .as_deref()
            .and_then(timeout_from_grub))
    }

    fn set_timeout(&self, ctx: &Context, timeout: Timeout) -> Result<Vec<WriteOutcome>> {
        ctx.preflight_write("timeout", &self.cfg)?;
        if ctx.dry_run {
            return Ok(Vec::new());
        }
        let value = timeout_to_grub(timeout);
        let mut outcomes = Vec::new();

        // Write the template so the change survives regeneration...
        if let Some(path) = self.default_grub_path() {
            let text = atomic::read_to_string(&path)?;
            let updated = default_grub_set(&text, "GRUB_TIMEOUT", &value);
            outcomes.push(atomic::write_atomic(&path, updated.as_bytes())?);
        }

        // ...and the generated menu so it takes effect on the next boot
        // without waiting for grub-mkconfig.
        let cfg_text = atomic::read_to_string(&self.cfg)?;
        let mut lines: Vec<String> = cfg_text.lines().map(str::to_string).collect();
        let mut patched = false;
        for line in lines.iter_mut() {
            if line.trim().starts_with("set timeout=") {
                let indent: String = line.chars().take_while(|c| c.is_whitespace()).collect();
                *line = format!("{indent}set timeout={value}");
                patched = true;
            }
        }
        if patched {
            let mut joined = lines.join("\n");
            joined.push('\n');
            outcomes.push(atomic::write_atomic(&self.cfg, joined.as_bytes())?);
        }

        Ok(outcomes)
    }

    fn set_cmdline(&self, ctx: &Context, entry: &BootEntry, cmdline: &str) -> Result<Vec<WriteOutcome>> {
        ctx.preflight_write("cmdline set", &self.cfg)?;

        let line_no = entry
            .extra
            .get("cfg-line")
            .and_then(|s| s.parse::<usize>().ok())
            .map(|n| n - 1)
            .ok_or_else(|| {
                Error::validation("this entry has no kernel line to edit".to_string())
            })?;

        if ctx.dry_run {
            return Ok(Vec::new());
        }

        let text = atomic::read_to_string(&self.cfg)?;
        let updated = rewrite_linux_line(&text, line_no, cmdline)?;
        Ok(vec![atomic::write_atomic(&self.cfg, updated.as_bytes())?])
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const CFG: &str = r#"
set default="${saved_entry}"
set timeout=5

menuentry 'Ubuntu' --class ubuntu $menuentry_id_option 'gnulinux-simple-abc' {
	recordfail
	linux	/vmlinuz-6.11.0-9-generic root=UUID=abc ro quiet splash
	initrd	/initrd.img-6.11.0-9-generic
}
submenu 'Advanced options for Ubuntu' $menuentry_id_option 'gnulinux-advanced-abc' {
	menuentry 'Ubuntu, with Linux 6.11.0-9-generic' $menuentry_id_option 'gnulinux-6.11.0-9-generic-advanced-abc' {
		linux	/vmlinuz-6.11.0-9-generic root=UUID=abc ro quiet splash
		initrd	/initrd.img-6.11.0-9-generic
	}
	menuentry 'Ubuntu, with Linux 6.11.0-9-generic (recovery mode)' $menuentry_id_option 'gnulinux-6.11.0-9-generic-recovery-abc' {
		linux	/vmlinuz-6.11.0-9-generic root=UUID=abc ro recovery nomodeset
		initrd	/initrd.img-6.11.0-9-generic
	}
}
menuentry 'Windows Boot Manager' $menuentry_id_option 'osprober-efi-1234' {
	chainloader /EFI/Microsoft/Boot/bootmgfw.efi
}
"#;

    #[test]
    fn tokenizes_quoted_titles() {
        let t = tokenize("menuentry 'Ubuntu, with Linux 6.11' --class os {");
        assert_eq!(t[0], "menuentry");
        assert_eq!(t[1], "Ubuntu, with Linux 6.11");
        assert_eq!(t[2], "--class");
    }

    #[test]
    fn brace_counting_ignores_braces_in_quotes() {
        assert_eq!(brace_delta("menuentry 'a {b}' {"), 1);
        assert_eq!(brace_delta("}"), -1);
        assert_eq!(brace_delta("# a comment with {"), 0);
        assert_eq!(brace_delta("if x; then { y } fi"), 0);
    }

    #[test]
    fn parses_top_level_entries() {
        let entries = parse_cfg(CFG);
        let ubuntu = &entries[0];
        assert_eq!(ubuntu.title, "Ubuntu");
        assert_eq!(ubuntu.id.as_deref(), Some("gnulinux-simple-abc"));
        assert_eq!(ubuntu.kernel.as_deref(), Some("/vmlinuz-6.11.0-9-generic"));
        assert_eq!(ubuntu.cmdline, "root=UUID=abc ro quiet splash");
        assert_eq!(ubuntu.initrds, vec!["/initrd.img-6.11.0-9-generic"]);
        assert_eq!(ubuntu.index_path, "0");
        assert_eq!(ubuntu.depth, 0);
    }

    #[test]
    fn parses_submenu_children_with_nested_indices() {
        let entries = parse_cfg(CFG);
        let submenu = entries.iter().find(|e| e.is_submenu).expect("submenu parsed");
        assert_eq!(submenu.index_path, "1");

        let child = entries
            .iter()
            .find(|e| e.title.contains("recovery mode"))
            .expect("nested entry parsed");
        assert_eq!(child.depth, 1);
        // GRUB addresses a submenu child as parent>child.
        assert_eq!(child.index_path, "1>1");
        assert!(child.cmdline.contains("recovery"));
    }

    #[test]
    fn counts_all_entries_including_chainloads() {
        let entries = parse_cfg(CFG);
        // 2 top-level menuentries + 1 submenu + 2 nested = 5.
        assert_eq!(entries.len(), 5);
        let windows = entries.iter().find(|e| e.title.contains("Windows")).unwrap();
        assert_eq!(windows.index_path, "2");
        assert!(windows.kernel.is_none());
    }

    #[test]
    fn records_the_linux_line_for_editing() {
        let entries = parse_cfg(CFG);
        let line = entries[0].linux_line.expect("linux line recorded");
        assert!(CFG.lines().nth(line).unwrap().contains("vmlinuz"));
    }

    #[test]
    fn parses_efi_and_16bit_kernel_keywords() {
        let cfg = "menuentry 'x' {\n\tlinuxefi /vmlinuz root=/dev/sda1\n\tinitrdefi /initrd.img\n}\n";
        let e = &parse_cfg(cfg)[0];
        assert_eq!(e.kernel.as_deref(), Some("/vmlinuz"));
        assert_eq!(e.cmdline, "root=/dev/sda1");
        assert_eq!(e.initrds, vec!["/initrd.img"]);
    }

    #[test]
    fn handles_multiple_initrds_on_one_line() {
        let cfg = "menuentry 'x' {\n\tlinux /vmlinuz\n\tinitrd /intel-ucode.img /initramfs.img\n}\n";
        assert_eq!(parse_cfg(cfg)[0].initrds, vec!["/intel-ucode.img", "/initramfs.img"]);
    }

    #[test]
    fn reads_default_grub_values() {
        let text = "GRUB_TIMEOUT=5\nGRUB_DEFAULT=saved\n\
                    GRUB_CMDLINE_LINUX_DEFAULT=\"quiet splash\"\n#GRUB_TERMINAL=console\n";
        assert_eq!(default_grub_get(text, "GRUB_TIMEOUT").as_deref(), Some("5"));
        assert_eq!(default_grub_get(text, "GRUB_DEFAULT").as_deref(), Some("saved"));
        assert_eq!(
            default_grub_get(text, "GRUB_CMDLINE_LINUX_DEFAULT").as_deref(),
            Some("quiet splash")
        );
        // Commented-out settings are not values.
        assert_eq!(default_grub_get(text, "GRUB_TERMINAL"), None);
    }

    #[test]
    fn writes_default_grub_preserving_comments() {
        let text = "# Distro defaults\nGRUB_TIMEOUT=5\nGRUB_DEFAULT=0\n";
        let out = default_grub_set(text, "GRUB_DEFAULT", "saved");
        assert!(out.contains("# Distro defaults"));
        assert!(out.contains("GRUB_TIMEOUT=5"));
        assert!(out.contains("GRUB_DEFAULT=\"saved\""));
        assert!(!out.contains("GRUB_DEFAULT=0"));
    }

    #[test]
    fn appends_a_missing_default_grub_key() {
        let out = default_grub_set("GRUB_TIMEOUT=5\n", "GRUB_DEFAULT", "saved");
        assert!(out.contains("GRUB_DEFAULT=\"saved\""));
        assert_eq!(default_grub_get(&out, "GRUB_DEFAULT").as_deref(), Some("saved"));
    }

    #[test]
    fn default_grub_round_trips_values_with_spaces() {
        let out = default_grub_set("", "GRUB_CMDLINE_LINUX_DEFAULT", "quiet splash loglevel=3");
        assert_eq!(
            default_grub_get(&out, "GRUB_CMDLINE_LINUX_DEFAULT").as_deref(),
            Some("quiet splash loglevel=3")
        );
    }

    #[test]
    fn converts_timeout_values() {
        assert_eq!(timeout_from_grub("5"), Some(Timeout::Seconds(5)));
        assert_eq!(timeout_from_grub("0"), Some(Timeout::Immediate));
        assert_eq!(timeout_from_grub("-1"), Some(Timeout::Indefinite));
        assert_eq!(timeout_to_grub(Timeout::Indefinite), "-1");
        for t in [Timeout::Immediate, Timeout::Seconds(9), Timeout::Indefinite] {
            assert_eq!(timeout_from_grub(&timeout_to_grub(t)), Some(t));
        }
    }

    #[test]
    fn rewrites_a_kernel_line_keeping_indent_and_path() {
        let entries = parse_cfg(CFG);
        let line = entries[0].linux_line.unwrap();
        let out = rewrite_linux_line(CFG, line, "root=UUID=abc ro debug").unwrap();

        assert!(out.contains("linux /vmlinuz-6.11.0-9-generic root=UUID=abc ro debug"));
        // Exactly one command line changed: the submenu child legitimately
        // carries the same parameters and must be left alone.
        assert_eq!(out.matches("quiet splash").count(), CFG.matches("quiet splash").count() - 1);
        // The rest of the file is untouched.
        assert!(out.contains("menuentry 'Windows Boot Manager'"));

        // And it re-parses to the new value.
        let reparsed = parse_cfg(&out);
        assert_eq!(reparsed[0].cmdline, "root=UUID=abc ro debug");
        assert_eq!(reparsed.len(), entries.len());
    }

    // ---- fixture-backed tests --------------------------------------------

    use crate::loaders::testsupport::{fake_kernel, Fixture, TempTree};

    fn grub_tree(tag: &str) -> TempTree {
        let tree = TempTree::new(tag);
        tree.file("grub/grub.cfg", CFG);
        let mut env = String::from(grubenv::SIGNATURE);
        env.push_str("saved_entry=gnulinux-simple-abc\n");
        env.push_str(&"#".repeat(grubenv::BLOCK_SIZE - env.len()));
        tree.file("grub/grubenv", &env);
        fake_kernel(&tree, "vmlinuz-6.11.0-9-generic");
        fake_kernel(&tree, "initrd.img-6.11.0-9-generic");
        tree
    }

    #[test]
    fn detects_grub_from_its_config() {
        let tree = grub_tree("grub-detect");
        let loader = Grub2::detect(&tree.roots()).expect("grub detected");
        assert_eq!(loader.cfg, tree.path("grub/grub.cfg"));
        // grubenv present means set-default works without regeneration.
        assert_eq!(loader.confidence, 92);
    }

    #[test]
    fn detects_the_grub2_directory_layout() {
        let tree = TempTree::new("grub-fedora");
        tree.file("grub2/grub.cfg", CFG);
        let loader = Grub2::detect(&tree.roots()).expect("grub2/ layout detected");
        assert!(loader.cfg.ends_with("grub2/grub.cfg"));
        assert_eq!(loader.confidence, 80);
    }

    #[test]
    fn marks_the_saved_entry_as_default() {
        let tree = grub_tree("grub-default");
        let fx = Fixture::rooted(tree.roots());
        let loader = Grub2::detect(&fx.roots).unwrap();

        let entries = loader.entries(&fx.context()).unwrap();
        let default = entries.iter().find(|e| e.is_default()).expect("a default is marked");
        assert_eq!(default.native_id, "gnulinux-simple-abc");
        assert_eq!(default.title, "Ubuntu");
    }

    #[test]
    fn resolves_kernel_paths_against_the_boot_root() {
        let tree = grub_tree("grub-paths");
        let fx = Fixture::rooted(tree.roots());
        let loader = Grub2::detect(&fx.roots).unwrap();

        let entries = loader.entries(&fx.context()).unwrap();
        assert_eq!(
            entries[0].kernel.as_ref().unwrap(),
            &tree.path("vmlinuz-6.11.0-9-generic")
        );
    }

    #[test]
    fn set_default_writes_the_environment_block() {
        let tree = grub_tree("grub-setdefault");
        let fx = Fixture::rooted(tree.roots());
        let loader = Grub2::detect(&fx.roots).unwrap();
        let entries = loader.entries(&fx.context()).unwrap();
        let recovery = entries.iter().find(|e| e.title.contains("recovery")).unwrap();

        loader.set_default(&fx.context(), recovery).unwrap();

        let env = GrubEnv::load(&tree.path("grub/grubenv")).unwrap();
        assert_eq!(env.get("saved_entry"), Some("gnulinux-6.11.0-9-generic-recovery-abc"));
        // The block must keep its exact size or GRUB will reject it.
        assert_eq!(std::fs::metadata(tree.path("grub/grubenv")).unwrap().len() as usize, grubenv::BLOCK_SIZE);
    }

    #[test]
    fn set_oneshot_writes_next_entry_and_clear_removes_it() {
        let tree = grub_tree("grub-oneshot");
        let fx = Fixture::rooted(tree.roots());
        let loader = Grub2::detect(&fx.roots).unwrap();
        let entries = loader.entries(&fx.context()).unwrap();
        let target = entries.iter().find(|e| e.title.contains("recovery")).unwrap();

        loader.set_oneshot(&fx.context(), target).unwrap();
        let env = GrubEnv::load(&tree.path("grub/grubenv")).unwrap();
        assert_eq!(env.get("next_entry"), Some("gnulinux-6.11.0-9-generic-recovery-abc"));

        // And the entry now reports the badge.
        let reread = loader.entries(&fx.context()).unwrap();
        assert!(reread.iter().any(|e| e.is_oneshot()));

        loader.clear_oneshot(&fx.context()).unwrap();
        assert_eq!(GrubEnv::load(&tree.path("grub/grubenv")).unwrap().get("next_entry"), None);
    }

    #[test]
    fn timeout_prefers_the_scan_s_default_grub_over_the_generated_config() {
        // Reproduces the case that made CI fail: a machine that has its own
        // /etc/default/grub while the scan is aimed at a different tree. The
        // value must come from the scan's config directory, never the host's.
        let tree = grub_tree("grub-scoped-etc");
        tree.file("etc/default/grub", "GRUB_TIMEOUT=0\nGRUB_DEFAULT=saved\n");

        let mut roots = tree.roots();
        roots.config = vec![tree.path("etc")];
        let fx = Fixture::rooted(roots);
        let loader = Grub2::detect(&fx.roots).unwrap();

        assert_eq!(loader.default_grub, Some(tree.path("etc/default/grub")));
        assert_eq!(loader.timeout(&fx.context()).unwrap(), Some(Timeout::Immediate));
        // And it is offered for backup alongside the generated config.
        assert!(loader.config_files().contains(&tree.path("etc/default/grub")));
    }

    #[test]
    fn a_scoped_scan_ignores_the_host_etc_entirely() {
        // With no config directories the adapter must fall back to grub.cfg
        // rather than reading whatever the running system happens to have.
        let tree = grub_tree("grub-no-etc");
        let fx = Fixture::rooted(tree.roots());
        let loader = Grub2::detect(&fx.roots).unwrap();

        assert_eq!(loader.default_grub, None);
        assert!(loader.config_files().iter().all(|p| p.starts_with(&tree.root)));
    }

    #[test]
    fn reads_timeout_from_the_generated_config() {
        let tree = grub_tree("grub-timeout");
        let fx = Fixture::rooted(tree.roots());
        let loader = Grub2::detect(&fx.roots).unwrap();
        // No /etc/default/grub in the fixture, so grub.cfg is consulted.
        assert_eq!(loader.timeout(&fx.context()).unwrap(), Some(Timeout::Seconds(5)));
    }

    #[test]
    fn set_cmdline_patches_the_generated_config() {
        let tree = grub_tree("grub-cmdline");
        let fx = Fixture::rooted(tree.roots());
        let loader = Grub2::detect(&fx.roots).unwrap();
        let entries = loader.entries(&fx.context()).unwrap();
        let ubuntu = entries.iter().find(|e| e.title == "Ubuntu").unwrap();

        loader.set_cmdline(&fx.context(), ubuntu, "root=UUID=abc ro debug").unwrap();

        let reread = loader.entries(&fx.context()).unwrap();
        let ubuntu = reread.iter().find(|e| e.title == "Ubuntu").unwrap();
        assert_eq!(ubuntu.cmdline, "root=UUID=abc ro debug");
        // Other entries keep their own command lines.
        assert!(reread.iter().any(|e| e.cmdline.contains("recovery")));
    }

    #[test]
    fn warns_that_the_generated_config_is_transient() {
        let tree = grub_tree("grub-note");
        let loader = Grub2::detect(&tree.roots()).unwrap();
        let note = loader.post_write_note().unwrap();
        assert!(note.contains("grub-mkconfig"));
    }

    #[test]
    fn writes_are_refused_without_root() {
        let tree = grub_tree("grub-noroot");
        let fx = Fixture::unprivileged(tree.roots());
        let loader = Grub2::detect(&fx.roots).unwrap();
        let entries = loader.entries(&fx.context()).unwrap();

        assert!(matches!(
            loader.set_default(&fx.context(), &entries[0]).unwrap_err(),
            Error::NeedsRoot { .. }
        ));
    }
}
